# Generated by Django 5.1.15 on 2026-09-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default='09:00:00', help_text='Official shift start time')),
                ('work_end_time', models.TimeField(default='17:00:00', help_text='Official shift end time')),
                ('late_grace_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after work_start_time before an attendance is marked LATE')),
                ('half_day_minimum_minutes', models.PositiveIntegerField(default=240, help_text='Minimum working duration for a half-day (in minutes)')),
                ('full_day_minimum_minutes', models.PositiveIntegerField(default=480, help_text='Minimum working duration for a full day (in minutes)')),
                ('timezone', models.CharField(default='Asia/Dhaka', help_text='Official company attendance timezone', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Setting',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(db_index=True, help_text='Calendar date of attendance in Asia/Dhaka timezone')),
                ('check_in_time', models.DateTimeField(help_text='Server-side recorded check-in timestamp')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Server-side recorded check-out timestamp', null=True)),
                ('working_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Total elapsed working duration in minutes', null=True)),
                ('attendance_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], db_index=True, default='AUTOMATIC', max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('INCOMPLETE', 'Incomplete'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='accounts.employee')),
                ('manual_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_attendance', to='requests.manualattendancerequest')),
            ],
            options={
                'ordering': ['-attendance_date', '-check_in_time'],
                'indexes': [models.Index(fields=['attendance_date', 'status'], name='attendance__attenda_f3ac94_idx'), models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_37ed17_idx'), models.Index(fields=['attendance_type'], name='attendance__attenda_0f11e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_date')],
            },
        ),
    ]
