# Generated by Django 5.1.15 on 2026-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters at check-in', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_distance_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in meters from assigned project site at check-in', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_is_geofence_violation',
            field=models.BooleanField(default=False, help_text='True if check-in was outside project geofence perimeter'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude captured at check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude captured at check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters at check-out', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_distance_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in meters from assigned project site at check-out', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_is_geofence_violation',
            field=models.BooleanField(default=False, help_text='True if check-out was outside project geofence perimeter'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude captured at check-out', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude captured at check-out', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='enforce_geofence',
            field=models.BooleanField(default=False, help_text='Strictly block check-in outside authorized site radius'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='require_gps',
            field=models.BooleanField(default=False, help_text='Require GPS coordinates during mobile check-in/out'),
        ),
    ]
