# Generated by Django 5.1.15 on 2026-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_check_in_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_address',
            field=models.CharField(blank=True, default='', help_text='Human-readable physical location address at check-in', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_address',
            field=models.CharField(blank=True, default='', help_text='Human-readable physical location address at check-out', max_length=255),
        ),
    ]
