# Generated by Django 5.1.15 on 2026-09-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('MANUAL_REQUEST_CREATED', 'Manual Request Created'), ('MANUAL_REQUEST_APPROVED', 'Manual Request Approved'), ('MANUAL_REQUEST_REJECTED', 'Manual Request Rejected'), ('ATTENDANCE_UPDATED', 'Attendance Updated'), ('USER_LOGIN', 'User Login'), ('USER_CREATED', 'User Created'), ('USER_DISABLED', 'User Disabled'), ('USER_ACTIVATED', 'User Activated'), ('USER_UPDATED', 'User Updated'), ('SETTING_UPDATED', 'Setting Updated')], db_index=True, max_length=60)),
                ('object_type', models.CharField(db_index=True, max_length=60)),
                ('object_id', models.CharField(db_index=True, max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
