# Generated by Django 5.1.15 on 2026-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Target latitude for geofenced site check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Target longitude for geofenced site check-in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='radius_meters',
            field=models.PositiveIntegerField(default=500, help_text='Geofence boundary radius in meters'),
        ),
    ]
