# Generated by Django 5.1.15 on 2026-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_latitude_project_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Assigned District / Zilla (e.g. Gazipur, Sylhet)', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.CharField(blank=True, default='', help_text='Bangladesh Division (e.g. Dhaka, Chattogram)', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='upazila',
            field=models.CharField(blank=True, default='', help_text='Assigned Upazila / Thana (e.g. Tongi, Sreepur)', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', help_text='District / Zilla (e.g. Gazipur, Cumilla)', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.CharField(blank=True, default='', help_text='Bangladesh Division (e.g. Dhaka, Chattogram)', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='upazila',
            field=models.CharField(blank=True, default='', help_text='Upazila / Thana (e.g. Tongi, Savar)', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Target latitude for geofenced site check-in (auto-populated from district center)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Target longitude for geofenced site check-in (auto-populated from district center)', max_digits=9, null=True),
        ),
    ]
