# Generated by Django 5.1.15 on 2026-09-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_project_latitude_project_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this holiday repeats annually on the same month/day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('EARNED', 'Earned / Annual Leave'), ('MATERNITY', 'Maternity / Paternity Leave'), ('OTHER', 'Other')], db_index=True, default='CASUAL', max_length=20)),
                ('start_date', models.DateField(db_index=True, help_text='Start date of leave period (inclusive)')),
                ('end_date', models.DateField(db_index=True, help_text='End date of leave period (inclusive)')),
                ('total_days', models.PositiveIntegerField(default=1, help_text='Total calendar days spanned by the leave request')),
                ('reason', models.TextField(help_text='Detailed justification or reason for leave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='', help_text='Reviewer comments or approval/rejection justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='leaves_leav_status_bca0ae_idx'), models.Index(fields=['employee', 'status'], name='leaves_leav_employe_7236fb_idx'), models.Index(fields=['start_date', 'end_date'], name='leaves_leav_start_d_96457d_idx')],
            },
        ),
    ]
